"""create Portfolio and PortfolioImage models

Revision ID: cce5f767edb5
Revises: 7edddb5d9228
Create Date: 2024-07-26 02:19:20.722850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cce5f767edb5"
down_revision: Union[str, None] = "7edddb5d9228"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("pharetra", sa.String(length=120), nullable=False),
        sa.Column("uorttitor", sa.String(length=120), nullable=False),
        sa.Column("quisque", sa.String(length=120), nullable=False),
        sa.Column("aliquet", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolio_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_image")
    op.drop_table("portfolio")
    # ### end Alembic commands ###
